---
name: Deploy DNS

on:
  push:
    branches:
      - main
    paths:
      - "dns/**"
  workflow_dispatch:

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml

  deploy:
    runs-on: ubuntu-20.04
    needs: [test-and-lint]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: solvaholic/octodns-sync@main
        with:
          config_path: dns/dns.yaml
          doit: "--doit"
