---
name: Dry Run Deploy

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  dry-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: solvaholic/octodns-sync@main
        with:
          config_path: dns/dns.yaml
          add_pr_comment: "Yes"
          pr_comment_token: "${{ github.token }}"
