---
name: Dry Run Deploy

on:
  pull_request:
  workflow_dispatch:

env:
  CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}

jobs:
  test-and-lint:
    uses: ./.github/workflows/test-and-lint.yaml

  dry-run:
    runs-on: ubuntu-latest
    needs: [test-and-lint]
    permissions:
      contents: read
      packages: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - uses: solvaholic/octodns-sync@main
        with:
          config_path: dns/dns.yaml
          add_pr_comment: "Yes"
          pr_comment_token: "${{ github.token }}"
