name: Run Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

env:
  CLOUDFLARE_TOKEN: dummy

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Lint (yaml)
        run: |
          set -ex
          pip install yamllint
          yamllint -s .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Check Configuration and Dependencies (octodns)
        run: |
          poetry run octodns-validate --config-file=dns/dns.yaml
